// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ToonVS
{
    internal sealed partial class Vsix
    {
        public const string Id = "ToonVS.a857d5f5-e2b1-485e-932b-893dbfaf3661";
        public const string Name = "Toon 2";
        public const string Description = @"Syntax highlighting for .toon files written according to the official specification";
        public const string Language = "en-US";
        public const string Version = "1.0.905";
        public const string Author = "Mads Kristensen";
        public const string Tags = "";
        public const bool IsPreview = false;
    }
}
