// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ToonVS
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string EditorFactoryString = "d89bf4d1-d10a-45dc-aa83-edc7c70b37ba";
        public static Guid EditorFactory = new Guid(EditorFactoryString);

        public const string ToonEditorString = "b096eacb-222a-4345-b21e-0d0bcd529f0a";
        public static Guid ToonEditor = new Guid(ToonEditorString);

        public const string JsonFileUIContextString = "3a1289f6-784f-42d1-b0ce-97bce72d969f";
        public static Guid JsonFileUIContext = new Guid(JsonFileUIContextString);

        public const string ToonVSString = "5feb63ae-63f8-4607-9178-6abea2125652";
        public static Guid ToonVS = new Guid(ToonVSString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ToggleCustomToolCommand = 0x0100;
    }
}
